
#import "AppDelegate.h"
#import "MFSideMenu.h"
#import "HomeViewController.h"
#import "LoginViewController.h"
#import "CustomCell.h"
#import "categoryCell.h"
#import "SearchViewController.h"
#import "RegisterViewController.h"
#import "CartViewController.h"
#import "UIImage+GIF.h"
#import "CheckoutViewController.h"
#import "WebViewController.h"
#import "HistoryViewController.h"
#import "ForgotViewController.h"
#import "ItemDetailViewController.h"
#import "AboutViewController.h"
#import "privacyViewController.h"
#import "DefaultViewController.h"
#import "ContactusViewController.h"
#import "TermsViewController.h"
#import "ImagefullviewViewController.h"
#import "TSCustomPickerController.h"
#import "NewItemDetailViewController.h"
#define baseURL "http://app.barakatfresh.ae/webservice/api/"
#define subURL "http://app.barakatfresh.ae/webservice/"
#define uAppDelegate (AppDelegate *)[[UIApplication sharedApplication] delegate]

